/*Given a string, we have to find out all its subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples: 

Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, a, a, aa, aa, aa, aaa

Time Complexity: O(n* 2^n)
Auxiliary Space: O(n)*/
import java.util.*;
class p28{
    public static void main(String[] args){
        Scanner sc=new Scanner(System.in);
        String s=sc.next();
        List<String> ls=new ArrayList<>();
        for(int i=1;i<(1<<s.length());i++){
            int j=0;
            String res="";
            int temp=i;
            while(temp>0){
                if((temp&1)>0){
                    res+=s.charAt(j);
                }
                j++;
                temp>>=1;
            }
            ls.add(res);
        }
        Collections.sort(ls);
        System.out.println(ls);
    }
}
